# Generated by Django 5.2.4 on 2026-07-27 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'expert group',
                'verbose_name_plural': 'expert groups',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertListingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=200, verbose_name='hero eyebrow')),
                ('hero_heading', models.CharField(max_length=400, verbose_name='hero heading')),
                ('hero_description', models.TextField(blank=True, verbose_name='hero description')),
                ('hero_image', models.ImageField(blank=True, upload_to='expert/hero/', verbose_name='hero background image')),
                ('hero_btn1_label', models.CharField(blank=True, default='TÌM HIỂU THÊM', max_length=100, verbose_name='button 1 label')),
                ('hero_btn1_url', models.CharField(blank=True, default='#ket-noi', max_length=500, verbose_name='button 1 URL')),
                ('hero_btn2_label', models.CharField(blank=True, default='ĐĂNG KÝ CHUYÊN GIA', max_length=100, verbose_name='button 2 label')),
                ('hero_btn2_url', models.CharField(blank=True, default='/lien-he/', max_length=500, verbose_name='button 2 URL')),
                ('process_heading', models.CharField(blank=True, max_length=300, verbose_name='process section heading')),
                ('process_description', models.TextField(blank=True, verbose_name='process section description')),
                ('senior_heading', models.CharField(blank=True, default='CHUYÊN GIA CAO CẤP CỦA VIỆN IRDM', max_length=300, verbose_name='senior experts section heading')),
                ('senior_cta_label', models.CharField(blank=True, default='Xem tất cả', max_length=100, verbose_name='senior section CTA label')),
                ('senior_cta_url', models.CharField(blank=True, default='#tim-kiem', max_length=500, verbose_name='senior section CTA URL')),
                ('map_heading', models.CharField(blank=True, default='BẢN ĐỒ CHUYÊN MÔN LIÊN NGÀNH', max_length=300, verbose_name='research area map heading')),
                ('map_description', models.TextField(blank=True, verbose_name='research area map description')),
                ('directory_heading', models.CharField(blank=True, default='TÌM NHÀ KHOA HỌC/CHUYÊN GIA', max_length=300, verbose_name='directory section heading')),
                ('topic_heading', models.CharField(blank=True, default='CÁC CHỦ ĐỀ THÔNG TIN CHUYÊN MÔN', max_length=300, verbose_name='knowledge topic section heading')),
                ('topic_description', models.TextField(blank=True, verbose_name='knowledge topic section description')),
                ('cta_eyebrow', models.CharField(blank=True, max_length=200, verbose_name='CTA eyebrow')),
                ('cta_heading', models.CharField(blank=True, max_length=400, verbose_name='CTA heading')),
                ('cta_description', models.TextField(blank=True, verbose_name='CTA description')),
                ('cta_bg_image', models.ImageField(blank=True, upload_to='expert/cta/', verbose_name='CTA background image')),
                ('cta_btn1_label', models.CharField(blank=True, default='LIÊN HỆ NGAY', max_length=100, verbose_name='CTA button 1 label')),
                ('cta_btn1_url', models.CharField(blank=True, default='/lien-he/', max_length=500, verbose_name='CTA button 1 URL')),
                ('cta_btn2_label', models.CharField(blank=True, default='ĐĂNG KÝ CHUYÊN GIA', max_length=100, verbose_name='CTA button 2 label')),
                ('cta_btn2_url', models.CharField(blank=True, default='/lien-he/', max_length=500, verbose_name='CTA button 2 URL')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
            ],
            options={
                'verbose_name': 'expert listing page',
                'verbose_name_plural': 'expert listing pages',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'knowledge topic',
                'verbose_name_plural': 'knowledge topics',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='step number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Heroicon name, e.g. 'document-text'", max_length=100, verbose_name='icon name')),
            ],
            options={
                'verbose_name': 'process step',
                'verbose_name_plural': 'process steps',
                'ordering': ['step_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, help_text="Heroicon name, e.g. 'chart-bar'", max_length=100, verbose_name='icon name')),
                ('color', models.CharField(blank=True, default='#1d4ed8', help_text='Hex color for the tag background, e.g. #1d4ed8', max_length=20, verbose_name='color (hex)')),
            ],
            options={
                'verbose_name': 'research area',
                'verbose_name_plural': 'research areas',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('academic_title', models.CharField(blank=True, help_text='e.g. GS.TS., PGS.TS., TS.', max_length=100, verbose_name='academic title')),
                ('position', models.CharField(blank=True, help_text='e.g. Giáo sư Kinh tế học, Phó Giáo sư Quản trị Kinh doanh', max_length=300, verbose_name='position/role')),
                ('organization', models.CharField(blank=True, help_text='Trường đại học hoặc tổ chức công tác', max_length=300, verbose_name='organization')),
                ('avatar', models.ImageField(blank=True, help_text='Portrait photo, recommended 400×400 px', upload_to='expert/avatars/', verbose_name='avatar')),
                ('short_bio', models.TextField(blank=True, help_text='1–3 sentences shown on listing card', verbose_name='short bio')),
                ('full_bio', models.TextField(blank=True, help_text='Full biography shown on detail page', verbose_name='full bio')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('profile_url', models.URLField(blank=True, help_text='Google Scholar, ResearchGate, personal website, etc.', verbose_name='external profile URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('is_senior', models.BooleanField(db_index=True, default=False, help_text="Show in 'Senior Experts' section on listing page", verbose_name='senior expert')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='expert.expertgroup', verbose_name='expert group')),
                ('knowledge_topics', models.ManyToManyField(blank=True, related_name='experts', to='expert.knowledgetopic', verbose_name='knowledge topics')),
                ('research_areas', models.ManyToManyField(blank=True, related_name='experts', to='expert.researcharea', verbose_name='research areas')),
            ],
            options={
                'verbose_name': 'expert',
                'verbose_name_plural': 'experts',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
