# Generated by Django 5.2.4 on 2026-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_badge_color',
            field=models.CharField(blank=True, default='#ffffff1a', help_text='Màu nền badge dạng hex hoặc rgba, e.g. #ffffff1a', max_length=30, verbose_name='hero badge color (hex)'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_badge_icon',
            field=models.CharField(blank=True, help_text="Heroicon name, e.g. 'users'. Để trống để dùng dot mặc định.", max_length=50, verbose_name='hero badge icon'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_badge_show',
            field=models.BooleanField(default=True, verbose_name='show hero badge'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='ĐỘI NGŨ CHUYÊN GIA', help_text='Badge label phía trên tiêu đề, e.g. ĐỘI NGŨ CHUYÊN GIA', max_length=200, verbose_name='hero badge text'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_bg',
            field=models.CharField(blank=True, default='#ffffff14', help_text='Màu nền bottom badge, e.g. #ffffff14', max_length=30, verbose_name='hero bottom badge bg color'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_icon',
            field=models.CharField(blank=True, help_text="Heroicon name cho bottom badge, e.g. 'chat-bubble-left-right'", max_length=50, verbose_name='hero bottom badge icon'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_show',
            field=models.BooleanField(default=True, verbose_name='show hero bottom badge'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_text',
            field=models.CharField(blank=True, default='ĐÚNG CHUYÊN MÔN CHO ĐÚNG BÀI TOÁN', help_text='Text hiển thị bên dưới CTA buttons, e.g. ĐÚNG CHUYÊN MÔN CHO ĐÚNG BÀI TOÁN', max_length=300, verbose_name='hero bottom badge text'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_btn1_icon',
            field=models.CharField(blank=True, help_text="Heroicon name, e.g. 'arrow-right'. Để trống nếu không dùng icon.", max_length=50, verbose_name='button 1 icon'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_btn1_target',
            field=models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_self', max_length=10, verbose_name='button 1 target'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_btn2_icon',
            field=models.CharField(blank=True, help_text="Heroicon name, e.g. 'arrow-right'. Để trống nếu không dùng icon.", max_length=50, verbose_name='button 2 icon'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_btn2_target',
            field=models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_self', max_length=10, verbose_name='button 2 target'),
        ),
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_btn1_label',
            field=models.CharField(blank=True, default='Tìm chuyên gia', max_length=100, verbose_name='button 1 label'),
        ),
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_btn2_label',
            field=models.CharField(blank=True, default='Xem lĩnh vực chuyên môn', max_length=100, verbose_name='button 2 label'),
        ),
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=200, verbose_name='hero eyebrow (legacy)'),
        ),
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_heading',
            field=models.CharField(help_text='Nhập Enter (\\n) để xuống dòng trong tiêu đề, e.g. MẠNG LƯỚI NHÀ KHOA HỌC\\n& CHUYÊN GIA LIÊN NGÀNH', max_length=400, verbose_name='hero heading'),
        ),
    ]
