# Generated by Django 5.2.4 on 2026-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_expertlistingpage_hero_badge_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_heading',
            field=models.TextField(help_text='Nhập Enter để xuống dòng trong tiêu đề. VD: MẠNG LƯỚI NHÀ KHOA HỌC (Enter) & CHUYÊN GIA LIÊN NGÀNH', verbose_name='hero heading'),
        ),
    ]
