# Generated by Django 5.2.4 on 2026-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_alter_expertlistingpage_hero_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_logo',
            field=models.ImageField(blank=True, help_text='Upload ảnh/logo hiển thị bên trái text badge. Ưu tiên hơn icon text.', upload_to='expert/hero/badges/', verbose_name='hero bottom badge logo'),
        ),
        migrations.AlterField(
            model_name='expertlistingpage',
            name='hero_bottom_badge_icon',
            field=models.CharField(blank=True, help_text="Chỉ dùng khi không upload logo ở trên. Heroicon name, e.g. 'chat-bubble-left-right'.", max_length=50, verbose_name='hero bottom badge icon (fallback)'),
        ),
    ]
