# Generated by Django 5.2.4 on 2026-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_expertlistingpage_hero_bottom_badge_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='process_section_label',
            field=models.CharField(blank=True, default='PHƯƠNG THỨC TIẾP CẬN', help_text='Nhãn nhỏ phía trên tiêu đề section, e.g. PHƯƠNG THỨC TIẾP CẬN. Để trống để ẩn.', max_length=100, verbose_name='process section label'),
        ),
    ]
