# Generated by Django 5.2.4 on 2026-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_expertlistingpage_process_section_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertlistingpage',
            name='process_heading',
            field=models.TextField(blank=True, help_text='Nhấn Enter để xuống dòng trong tiêu đề. VD: VIỆN IRDM KẾT NỐI CHUYÊN GIA (Enter) NHƯ THẾ NÀO?', verbose_name='process section heading'),
        ),
    ]
