# Generated by Django 5.2.4 on 2026-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_alter_expertlistingpage_process_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='senior_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn bên dưới tiêu đề section chuyên gia cao cấp.', verbose_name='senior section description'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='senior_section_label',
            field=models.CharField(blank=True, default='CHUYÊN GIA CẤP CAO', help_text='Nhãn nhỏ phía trên tiêu đề section. Để trống để ẩn.', max_length=100, verbose_name='senior section label'),
        ),
    ]
