# Generated by Django 5.2.4 on 2026-07-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_expertlistingpage_senior_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='map_cta1_label',
            field=models.CharField(blank=True, default='Tìm chuyên gia', max_length=100, verbose_name='map CTA 1 label'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='map_cta1_url',
            field=models.CharField(blank=True, default='#tim-kiem', max_length=500, verbose_name='map CTA 1 URL'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='map_cta2_label',
            field=models.CharField(blank=True, default='Khám phá giải pháp', max_length=100, verbose_name='map CTA 2 label'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='map_cta2_url',
            field=models.CharField(blank=True, default='/giai-phap/', max_length=500, verbose_name='map CTA 2 URL'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='map_section_label',
            field=models.CharField(blank=True, default='BẢN ĐỒ CHUYÊN MÔN', help_text='Nhãn nhỏ phía trên tiêu đề section. Để trống để ẩn.', max_length=100, verbose_name='map section label'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='card_tags',
            field=models.TextField(blank=True, help_text='Mỗi tag một dòng (nhấn Enter để xuống dòng). VD:\nY tế\nHệ thống y tế\nAI dữ liệu', verbose_name='card tags'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị trong card bản đồ chuyên môn (2-3 câu).', verbose_name='description'),
        ),
    ]
