# Generated by Django 5.2.4 on 2026-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_expertlistingpage_map_cta1_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharea',
            name='card_cta_label',
            field=models.CharField(blank=True, default='Tìm chuyên gia liên quan', help_text="Nhãn nút CTA trong card, e.g. 'Tìm chuyên gia liên quan'", max_length=200, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='card_cta_url',
            field=models.CharField(blank=True, default='/chuyen-gia/', help_text='Đường dẫn khi nhấn CTA, e.g. /chuyen-gia/?linh-vuc=kinh-te', max_length=500, verbose_name='CTA URL'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='icon',
            field=models.CharField(blank=True, choices=[('chart-bar', '📊 chart-bar — Kinh tế / Thống kê'), ('briefcase', '💼 briefcase — Quản trị / Lãnh đạo'), ('cpu', '🖥️ cpu — Công nghệ / AI'), ('building-library', '🏛️ building-library — Chính sách / Pháp luật'), ('leaf', '🌿 leaf — Bền vững / Môi trường'), ('academic-cap', '🎓 academic-cap — Giáo dục / Đào tạo'), ('heart', '❤️ heart — Y tế / Sức khoẻ'), ('light-bulb', '💡 light-bulb — Đổi mới sáng tạo'), ('globe-alt', '🌐 globe-alt — Quốc tế / Toàn cầu'), ('users', '👥 users — Nhân lực / Cộng đồng'), ('beaker', '🔬 beaker — Nghiên cứu / Khoa học'), ('currency-dollar', '💵 currency-dollar — Tài chính / Đầu tư')], help_text='Chọn icon đại diện cho lĩnh vực chuyên môn.', max_length=100, verbose_name='icon name'),
        ),
    ]
