# Generated by Django 5.2.4 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_researcharea_icon_choices_cta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharea',
            name='card_icon',
            field=models.ImageField(blank=True, help_text='Upload icon PNG/SVG (~40×40 px). Nếu upload thì ưu tiên hiển thị, nếu không sẽ dùng icon từ danh sách bên trên.', upload_to='expert/area-icons/', verbose_name='card icon'),
        ),
    ]
