# Generated by Django 5.2.4 on 2026-07-28 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_researcharea_card_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'engagement type',
                'verbose_name_plural': 'engagement types',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='directory_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị bên dưới tiêu đề section tìm kiếm.', verbose_name='directory section description'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='directory_section_label',
            field=models.CharField(blank=True, default='TÌM KIẾM', help_text='Nhãn nhỏ phía trên tiêu đề section. Để trống để ẩn.', max_length=100, verbose_name='directory section label'),
        ),
        migrations.AddField(
            model_name='expert',
            name='engagement_types',
            field=models.ManyToManyField(blank=True, help_text='Hình thức đồng hành: Tư vấn chiến lược, Đào tạo, Nghiên cứu, v.v.', related_name='experts', to='expert.engagementtype', verbose_name='engagement types'),
        ),
    ]
