# Generated by Django 5.2.4 on 2026-07-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0011_engagementtype_directory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgetopic',
            name='color',
            field=models.CharField(blank=True, help_text='Màu accent cho badge số thứ tự, e.g. #1B3F6E. Để trống dùng màu mặc định.', max_length=30, verbose_name='accent color (hex)'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='cta_label',
            field=models.CharField(blank=True, help_text="Nhãn nút CTA bên dưới danh sách chuyên gia, e.g. 'Xem tất cả'. Để trống để ẩn.", max_length=100, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Đường dẫn của nút CTA, e.g. /chuyen-gia/?chu-de=chuyen-doi-so', max_length=500, verbose_name='CTA URL'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='icon',
            field=models.CharField(blank=True, help_text="Heroicon name, e.g. 'cpu-chip', 'leaf', 'chart-bar'. Hiển thị cạnh số thứ tự.", max_length=50, verbose_name='icon'),
        ),
    ]
