# Generated by Django 5.2.4 on 2026-07-29 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_knowledgetopic_icon_color_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlistingpage',
            name='topic_section_label',
            field=models.CharField(blank=True, help_text='Nhãn nhỏ phía trên tiêu đề section (hiển thị chữ nhỏ, in hoa). Để trống để ẩn.', max_length=200, verbose_name='knowledge topic section label'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='body_description',
            field=models.TextField(blank=True, help_text="Đoạn mô tả bên trong phần mở rộng, bên dưới tiêu đề. Chỉ dùng cho loại 'Cơ cấu tổ chức'.", verbose_name='mô tả nội dung'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='body_heading',
            field=models.TextField(blank=True, help_text="Tiêu đề in đậm bên trong phần mở rộng. Chỉ dùng cho loại 'Cơ cấu tổ chức'.", verbose_name='tiêu đề nội dung'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='body_label',
            field=models.CharField(blank=True, help_text="Nhãn nhỏ uppercase bên trong phần mở rộng, e.g. 'CƠ CẤU TỔ CHỨC'. Chỉ dùng cho loại 'Cơ cấu tổ chức'.", max_length=200, verbose_name='nhãn tiêu đề nội dung'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='topic_type',
            field=models.CharField(choices=[('expert_list', 'Danh sách chuyên gia'), ('org_chart', 'Cơ cấu tổ chức')], default='expert_list', help_text="Chọn 'Danh sách chuyên gia' để hiển thị expert grid; 'Cơ cấu tổ chức' để hiển thị sơ đồ tổ chức.", max_length=20, verbose_name='loại nội dung'),
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='tên đơn vị')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Cấp 0 — Ban/Hội đồng (cấp cao nhất)'), (1, 'Cấp 1 — Giám đốc/Viện trưởng'), (2, 'Cấp 2 — Phòng/Ban')], default=2, help_text='Xác định vị trí trong sơ đồ tổ chức.', verbose_name='cấp độ')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Hiển thị dạng box xanh đậm (dùng cho Hội đồng/Ban cấp cao nhất).', verbose_name='nổi bật (nền xanh đậm)')),
                ('function', models.TextField(blank=True, help_text='Mô tả ngắn về chức năng của đơn vị. Hiển thị bên dưới sơ đồ.', verbose_name='chức năng')),
                ('duties', models.TextField(blank=True, help_text='Mỗi dòng là một nhiệm vụ → hiển thị dạng bullet list. Nhấn Enter để thêm dòng mới.', verbose_name='nhiệm vụ chính')),
                ('topic', models.ForeignKey(limit_choices_to={'topic_type': 'org_chart'}, on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='expert.knowledgetopic', verbose_name='knowledge topic')),
            ],
            options={
                'verbose_name': 'org unit',
                'verbose_name_plural': 'org units',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
