# Generated by Django 5.2.4 on 2026-07-29 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0013_orgunit_topic_type_section_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, help_text="Heroicon name hiển thị trong header accordion, e.g. 'building-office-2', 'academic-cap'.", max_length=50, verbose_name='icon')),
                ('icon_bg_color', models.CharField(blank=True, default='#EFF6FF', help_text='Màu nền ô icon, e.g. #EFF6FF (blue-50). Để trống dùng màu mặc định.', max_length=30, verbose_name='icon background color (hex)')),
                ('header_description', models.TextField(blank=True, help_text='Mô tả ngắn hiển thị trong phần header accordion (bên dưới tiêu đề).', verbose_name='header description')),
                ('section_label', models.CharField(blank=True, help_text="Nhãn nhỏ màu primary bên trên tiêu đề trong phần body, e.g. 'CƠ CẤU TỔ CHỨC'.", max_length=100, verbose_name='body section label')),
                ('section_heading', models.TextField(blank=True, help_text='Tiêu đề đậm chính trong phần body mở rộng.', verbose_name='body section heading')),
                ('section_description', models.TextField(blank=True, help_text='Đoạn mô tả bên dưới tiêu đề trong phần body.', verbose_name='body section description')),
                ('body_html', models.TextField(blank=True, help_text='Nội dung HTML tùy ý cho phần body (sơ đồ tổ chức, bảng, danh sách…). Chỉ admin mới chỉnh sửa — nội dung được render trực tiếp.', verbose_name='body HTML content')),
            ],
            options={
                'verbose_name': 'info group',
                'verbose_name_plural': 'info groups',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='expertlistingpage',
            name='topic_section_label',
        ),
        migrations.RemoveField(
            model_name='knowledgetopic',
            name='body_description',
        ),
        migrations.RemoveField(
            model_name='knowledgetopic',
            name='body_heading',
        ),
        migrations.RemoveField(
            model_name='knowledgetopic',
            name='body_label',
        ),
        migrations.RemoveField(
            model_name='knowledgetopic',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='info_group_section_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị bên dưới tiêu đề section.', verbose_name='info group section description'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='info_group_section_heading',
            field=models.CharField(blank=True, default='CÁC NHÓM THÔNG TIN CHUYÊN MÔN', max_length=300, verbose_name='info group section heading'),
        ),
        migrations.AddField(
            model_name='expertlistingpage',
            name='info_group_section_label',
            field=models.CharField(blank=True, default='CÁC NHÓM THÔNG TIN CHUYÊN MÔN', help_text='Nhãn nhỏ phía trên tiêu đề section. Để trống để ẩn.', max_length=100, verbose_name='info group section label'),
        ),
        migrations.DeleteModel(
            name='OrgUnit',
        ),
    ]
