# Generated by Django 5.2.4 on 2026-07-29 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0014_add_infogroup_and_listing_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogroup',
            name='body_html',
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='header_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị trong header accordion (bên dưới tiêu đề).', verbose_name='header description'),
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='icon',
            field=models.CharField(blank=True, choices=[('building-office-2', '🏢 building-office-2 — Cơ cấu tổ chức'), ('academic-cap', '🎓 academic-cap — Hội đồng khoa học'), ('users', '👥 users — Nhà khoa học & Chuyên gia'), ('chart-bar', '📊 chart-bar — Thống kê / Kinh tế'), ('briefcase', '💼 briefcase — Quản trị / Lãnh đạo'), ('beaker', '🔬 beaker — Nghiên cứu / Khoa học'), ('light-bulb', '💡 light-bulb — Đổi mới sáng tạo'), ('globe-alt', '🌐 globe-alt — Quốc tế / Toàn cầu'), ('document-text', '📄 document-text — Tài liệu / Chính sách'), ('star', '⭐ star — Nổi bật')], help_text='Icon hiển thị trong header accordion.', max_length=50, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='icon_bg_color',
            field=models.CharField(blank=True, default='#EFF6FF', help_text='Màu nền ô icon, e.g. #EFF6FF. Để trống dùng màu mặc định.', max_length=30, verbose_name='icon background color (hex)'),
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='section_label',
            field=models.CharField(blank=True, help_text="Nhãn nhỏ uppercase bên trên tiêu đề body, e.g. 'CƠ CẤU TỔ CHỨC'.", max_length=100, verbose_name='body section label'),
        ),
        migrations.CreateModel(
            name='InfoGroupBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('function_label', models.CharField(blank=True, default='CHỨC NĂNG', help_text='Nhãn nhỏ uppercase trên đoạn mô tả chức năng.', max_length=100, verbose_name='function label')),
                ('function_text', models.TextField(blank=True, help_text='Đoạn mô tả chức năng của đơn vị.', verbose_name='function text')),
                ('duties_label', models.CharField(blank=True, default='NHIỆM VỤ CHÍNH', help_text='Nhãn nhỏ uppercase trên danh sách nhiệm vụ.', max_length=100, verbose_name='duties label')),
                ('duties', models.TextField(blank=True, help_text='Mỗi dòng là một nhiệm vụ → bullet list. Nhấn Enter để thêm dòng.', verbose_name='duties (one per line)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('info_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='expert.infogroup', verbose_name='info group')),
            ],
            options={
                'verbose_name': 'info group block',
                'verbose_name_plural': 'info group blocks',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='node name')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Cấp 0 — Hội đồng/Ban cấp cao nhất'), (1, 'Cấp 1 — Giám đốc/Viện trưởng'), (2, 'Cấp 2 — Phòng/Ban/Đơn vị')], default=2, help_text='Cấp độ trong sơ đồ tổ chức. Xác định vị trí và kiểu hiển thị mặc định.', verbose_name='level')),
                ('style', models.CharField(choices=[('filled', 'Filled — Nền xanh đậm, chữ trắng (vd: Hội đồng)'), ('outlined', 'Outlined — Viền xanh, nền trắng (vd: Viện trưởng)'), ('default', 'Default — Viền xám, nền trắng (vd: Phòng/Ban)')], default='default', help_text='Kiểu hiển thị của node.', max_length=20, verbose_name='style')),
                ('color', models.CharField(blank=True, help_text='Màu nền tùy chỉnh (hex), e.g. #1B3F6E. Để trống dùng màu theo style.', max_length=30, verbose_name='custom color (hex)')),
                ('url', models.CharField(blank=True, help_text='Đường dẫn khi click vào node. Để trống nếu không cần link.', max_length=500, verbose_name='URL')),
                ('info_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_nodes', to='expert.infogroup', verbose_name='info group')),
                ('parent', models.ForeignKey(blank=True, help_text='Node cha trong cây tổ chức. Để trống nếu là node gốc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='expert.orgnode', verbose_name='parent node')),
            ],
            options={
                'verbose_name': 'org node',
                'verbose_name_plural': 'org nodes',
                'ordering': ['level', 'display_order'],
                'abstract': False,
            },
        ),
    ]
