# Generated by Django 5.2.4 on 2026-07-29 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_orgnode_infogroupblock_remove_bodyhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, help_text="Nhãn vai trò hiển thị trên badge, vd: 'Chủ tịch Hội đồng', 'Thư ký Hội đồng'.", max_length=100, verbose_name='role label')),
                ('academic_title', models.CharField(blank=True, help_text='Học hàm/học vị, vd: GS.TS., PGS.TS., ThS., TS.', max_length=100, verbose_name='academic title')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('position', models.CharField(blank=True, help_text='Chức danh / đơn vị công tác (tùy chọn).', max_length=300, verbose_name='position')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện, recommended 200×200 px.', upload_to='expert/council/', verbose_name='avatar')),
                ('cta_text', models.CharField(blank=True, default='Xem hồ sơ chuyên môn', help_text="Nhãn nút CTA bên dưới card, vd: 'Xem hồ sơ chuyên môn'.", max_length=100, verbose_name='CTA text')),
                ('cta_url', models.CharField(blank=True, help_text='Đường dẫn trang hồ sơ chuyên môn. Để trống nếu không cần link.', max_length=500, verbose_name='CTA URL')),
                ('info_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='expert.infogroup', verbose_name='info group')),
            ],
            options={
                'verbose_name': 'info group member',
                'verbose_name_plural': 'info group members',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
