# Generated by Django 5.2.4 on 2026-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_add_infogroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogroup',
            name='expert_grid_cta_label',
            field=models.CharField(blank=True, default='Xem hồ sơ chuyên môn', help_text="Nhãn nút CTA bên dưới mỗi expert card, e.g. 'Xem hồ sơ chuyên môn'.", max_length=100, verbose_name='expert grid CTA label'),
        ),
        migrations.AddField(
            model_name='infogroup',
            name='expert_research_areas',
            field=models.ManyToManyField(blank=True, help_text="Chọn các nhóm chuyên môn sẽ hiển thị trong lưới chuyên gia. Thứ tự hiển thị theo 'display_order' của từng Lĩnh vực chuyên môn.", related_name='info_groups', to='expert.researcharea', verbose_name='expert research areas'),
        ),
        migrations.AddField(
            model_name='infogroup',
            name='show_expert_grid',
            field=models.BooleanField(default=False, help_text='Khi bật, accordion hiển thị lưới chuyên gia theo nhóm chuyên môn thay vì sơ đồ tổ chức / khối mô tả.', verbose_name='show expert grid'),
        ),
    ]
