# Generated by Django 5.2.4 on 2026-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0017_infogroup_expert_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogroup',
            name='expert_direct_members',
            field=models.ManyToManyField(blank=True, help_text="Chọn chuyên gia hiển thị trực tiếp trong lưới phẳng. Chỉ dùng khi bật 'flat expert grid'. Thứ tự hiển thị theo 'display_order' của từng chuyên gia.", related_name='direct_info_groups', to='expert.expert', verbose_name='direct expert members'),
        ),
        migrations.AddField(
            model_name='infogroup',
            name='expert_grid_flat',
            field=models.BooleanField(default=False, help_text="Khi bật cùng với 'show expert grid', hiển thị danh sách chuyên gia theo lưới phẳng (không tách nhóm theo lĩnh vực) — dùng cho accordion Giảng viên.", verbose_name='flat expert grid'),
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='icon',
            field=models.CharField(blank=True, choices=[('building-office-2', '🏢 building-office-2 — Cơ cấu tổ chức'), ('academic-cap', '🎓 academic-cap — Hội đồng khoa học'), ('users', '👥 users — Nhà khoa học & Chuyên gia'), ('book-open', '📖 book-open — Giảng viên & Học tập ứng dụng'), ('chart-bar', '📊 chart-bar — Thống kê / Kinh tế'), ('briefcase', '💼 briefcase — Quản trị / Lãnh đạo'), ('beaker', '🔬 beaker — Nghiên cứu / Khoa học'), ('light-bulb', '💡 light-bulb — Đổi mới sáng tạo'), ('globe-alt', '🌐 globe-alt — Quốc tế / Toàn cầu'), ('document-text', '📄 document-text — Tài liệu / Chính sách'), ('star', '⭐ star — Nổi bật')], help_text='Icon hiển thị trong header accordion.', max_length=50, verbose_name='icon'),
        ),
    ]
