# Generated by Django 5.2.4 on 2026-07-29 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0018_infogroup_flat_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogroup',
            name='show_association_grid',
            field=models.BooleanField(default=False, help_text="Khi bật, accordion hiển thị lưới thẻ Hiệp hội/Mạng lưới — dùng cho accordion Hiệp hội & Mạng lưới chuyên môn. Quản lý từng hiệp hội trong mục 'Hiệp hội/Mạng lưới' (inline bên dưới).", verbose_name='show association grid'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo PNG/JPG của hiệp hội/mạng lưới. Recommended ≥1:1, ≥200px. Ưu tiên hơn icon.', upload_to='expert/associations/', verbose_name='logo')),
                ('icon', models.CharField(blank=True, choices=[('globe-alt', '🌐 globe-alt — Quốc tế / Mạng lưới'), ('academic-cap', '🎓 academic-cap — Học thuật'), ('building-library', '🏙 building-library — Tổ chức / Hiệp hội'), ('users', '👥 users — Cộng đồng / Mạng lưới'), ('briefcase', '💼 briefcase — Nghề nghiệp / Doanh nghiệp'), ('beaker', '🔬 beaker — Nghiên cứu / Khoa học'), ('cpu-chip', '🧠 cpu-chip — Công nghệ / AI'), ('heart', '❤️ heart — Y tế / Sức khoẻ'), ('light-bulb', '💡 light-bulb — Đổi mới'), ('chart-bar', '📊 chart-bar — Dữ liệu / Thống kê')], help_text='Heroicon hiển thị khi không có logo. Chọn từ danh sách.', max_length=50, verbose_name='icon (fallback)')),
                ('icon_bg_color', models.CharField(blank=True, default='#EFF6FF', help_text='Màu nền ô icon khi không có logo, e.g. #EFF6FF.', max_length=30, verbose_name='icon background color (hex)')),
                ('badge_label', models.CharField(blank=True, help_text="Nhãn vai trò, e.g. 'Thành viên và Ban điều hành mở rộng'.", max_length=200, verbose_name='badge label')),
                ('badge_color', models.CharField(blank=True, default='#EC6D29', help_text='Màu chữ badge, e.g. #EC6D29 (cam brand). Để trống dùng màu mặc định.', max_length=30, verbose_name='badge color (hex)')),
                ('title', models.CharField(help_text='Tên đầy đủ của hiệp hội/mạng lưới.', max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Mô tả ngắn về vai trò và gia trị của việc tham gia (2-5 câu).', verbose_name='description')),
                ('cta_label', models.CharField(blank=True, default='Tìm hiểu thêm', help_text="Nhãn nút CTA, e.g. 'Tìm hiểu thêm'.", max_length=100, verbose_name='CTA label')),
                ('cta_url', models.CharField(blank=True, help_text='URL đến trang chi tiết hiệp hội hoặc website bên ngoài.', max_length=500, verbose_name='CTA URL')),
                ('cta_target', models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_blank', help_text='_blank để mở website bên ngoài. _self cho trang nội bộ.', max_length=10, verbose_name='CTA target')),
                ('info_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='expert.infogroup', verbose_name='info group')),
            ],
            options={
                'verbose_name': 'association',
                'verbose_name_plural': 'associations',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
