# Generated by Django 5.2.4 on 2026-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0020_expert_card_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='contact_cta_url',
            field=models.CharField(blank=True, default='/lien-he/', help_text="URL nút 'Liên hệ hợp tác' trên hero, e.g. /lien-he/ hoặc mailto:email@irdm.edu.vn", max_length=500, verbose_name='contact CTA URL'),
        ),
        migrations.AddField(
            model_name='expert',
            name='discussion_topics',
            field=models.TextField(blank=True, help_text='Các chủ đề có thể đồng hành, mỗi dòng một chủ đề (hiển thị 2 cột), e.g.:\nChiến lược phát triển Giáo dục đại học\nPhát triển chương trình đào tạo theo chuẩn đầu ra', verbose_name='discussion topics'),
        ),
        migrations.AddField(
            model_name='expert',
            name='experience_highlights',
            field=models.TextField(blank=True, help_text='Các kinh nghiệm nổi bật, mỗi dòng một mục (hiển thị đánh số tự động), e.g.:\nNguyên Hiệu trưởng Đại học Cần Thơ\nChủ tịch Hội đồng Đảm bảo Chất lượng', verbose_name='experience highlights'),
        ),
        migrations.AddField(
            model_name='expert',
            name='hero_tagline',
            field=models.TextField(blank=True, help_text="Đoạn tagline in đậm hiển thị trên hero, e.g. 'Chuyên gia cao cấp về quản trị đại học...'", verbose_name='hero tagline'),
        ),
        migrations.AddField(
            model_name='expert',
            name='notable_projects',
            field=models.TextField(blank=True, help_text='Dự án / Công trình / Chương trình tiêu biểu, mỗi dòng một mục, e.g.:\nChủ nhiệm dự án phát triển đại học quốc tế VLIR (Bỉ)\nThiết kế chương trình Thạc sĩ Quản lý Môi trường', verbose_name='notable projects'),
        ),
        migrations.AddField(
            model_name='expert',
            name='role_badges',
            field=models.TextField(blank=True, help_text='Mỗi dòng là một badge vai trò, e.g.:\nThành viên Hội đồng quản lý IRDM\nNhà khoa học/chuyên gia', verbose_name='role badges'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_1_label',
            field=models.CharField(blank=True, help_text="e.g. 'Năm kinh nghiệm'", max_length=200, verbose_name='stat 1 — label'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_1_value',
            field=models.CharField(blank=True, help_text="e.g. '40+'", max_length=50, verbose_name='stat 1 — value'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_2_label',
            field=models.CharField(blank=True, help_text="e.g. 'Trường đại học tư vấn'", max_length=200, verbose_name='stat 2 — label'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_2_value',
            field=models.CharField(blank=True, help_text="e.g. '100+'", max_length=50, verbose_name='stat 2 — value'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_3_label',
            field=models.CharField(blank=True, help_text="e.g. 'Phạm vi nghiên cứu và hợp tác quốc tế'", max_length=200, verbose_name='stat 3 — label'),
        ),
        migrations.AddField(
            model_name='expert',
            name='stat_3_value',
            field=models.CharField(blank=True, help_text="e.g. 'ASEAN'", max_length=50, verbose_name='stat 3 — value'),
        ),
        migrations.AddField(
            model_name='expert',
            name='ticker_text',
            field=models.CharField(blank=True, help_text="Văn bản chạy ngang dưới hero, e.g. 'QUẢN TRỊ ĐẠI HỌC ❖ CHÍNH SÁCH CÔNG ❖ PHÁT TRIỂN BỀN VỮNG'", max_length=500, verbose_name='ticker bar text'),
        ),
    ]
