# Generated by Django 5.2.4 on 2026-08-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthero',
            name='quote_show',
            field=models.BooleanField(default=True, verbose_name='show quote'),
        ),
        migrations.AddField(
            model_name='abouthero',
            name='quote_text',
            field=models.CharField(blank=True, help_text='Short inspirational quote shown below the CTA buttons', max_length=500, verbose_name='quote text'),
        ),
    ]
