# Generated by Django 5.2.4 on 2026-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_add_quote_to_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthero',
            name='quote_icon',
            field=models.ImageField(blank=True, help_text='Icon image shown left of the quote (PNG/SVG ~28×28px). Falls back to default chat-bubble icon if empty.', upload_to='about/hero/quote/', verbose_name='quote icon'),
        ),
    ]
