# Generated by Django 5.2.4 on 2026-08-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_add_quote_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutintroduction',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='about/intro/bg/', verbose_name='background image'),
        ),
    ]
