# Generated by Django 5.2.4 on 2026-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_add_bg_image_to_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpurpose',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='about/purpose/bg/', verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='aboutpurpose',
            name='diagram_caption',
            field=models.CharField(blank=True, max_length=400, verbose_name='diagram caption'),
        ),
        migrations.AddField(
            model_name='aboutpurpose',
            name='diagram_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='diagram card title'),
        ),
        migrations.AddField(
            model_name='aboutpurpose',
            name='quote_body',
            field=models.TextField(blank=True, verbose_name='quote body text'),
        ),
        migrations.AddField(
            model_name='aboutpurpose',
            name='quote_icon',
            field=models.ImageField(blank=True, upload_to='about/purpose/icons/', verbose_name='quote icon image'),
        ),
        migrations.AlterField(
            model_name='aboutpurpose',
            name='highlight_box_text',
            field=models.TextField(blank=True, verbose_name='quote text (bold)'),
        ),
    ]
