# Generated by Django 5.2.4 on 2026-08-02 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_extend_purpose_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutvisionmission',
            name='bottom_panel_description',
            field=models.TextField(blank=True, verbose_name='bottom panel description'),
        ),
        migrations.AddField(
            model_name='aboutvisionmission',
            name='bottom_panel_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='bottom panel title'),
        ),
        migrations.AddField(
            model_name='aboutvisionmissioncard',
            name='highlight_label',
            field=models.CharField(blank=True, help_text="Short label shown at card bottom e.g. 'Định hướng tương lai'", max_length=200, verbose_name='highlight label'),
        ),
        migrations.CreateModel(
            name='AboutVisionMissionIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon_image', models.ImageField(blank=True, upload_to='about/vision/panel_icons/', verbose_name='icon image')),
                ('icon_alt', models.CharField(blank=True, max_length=200, verbose_name='icon alt text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_icons', to='about.aboutvisionmission', verbose_name='section')),
            ],
            options={
                'verbose_name': 'vision/mission panel icon',
                'verbose_name_plural': 'vision/mission panel icons',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
