# Generated by Django 5.2.4 on 2026-08-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_vision_mission_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcorevaluesection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image overlaid on the Core Values section.', upload_to='about/core_values/', verbose_name='background image'),
        ),
    ]
