# Generated by Django 5.2.4 on 2026-08-02 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_core_value_section_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='about/legal/bg/', verbose_name='background decoration'),
        ),
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='footer_note',
            field=models.TextField(blank=True, verbose_name='footer note'),
        ),
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='footer_note_show',
            field=models.BooleanField(default=False, verbose_name='show footer note'),
        ),
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='org_card_label',
            field=models.CharField(blank=True, default='THÔNG TIN TỔ CHỨC', max_length=100, verbose_name='org card label'),
        ),
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='org_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='organisation name'),
        ),
        migrations.AddField(
            model_name='aboutlegalinfo',
            name='timeline_card_title',
            field=models.CharField(blank=True, default='CỘT MỐC PHÁP LÝ', max_length=200, verbose_name='timeline card title'),
        ),
        migrations.AddField(
            model_name='aboutlegaltimelineitem',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='about/legal/icons/', verbose_name='icon image'),
        ),
        migrations.CreateModel(
            name='AboutLegalBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('legal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_badges', to='about.aboutlegalinfo', verbose_name='legal section')),
            ],
            options={
                'verbose_name': 'org badge',
                'verbose_name_plural': 'org badges',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutLegalOrgAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200, verbose_name='label')),
                ('value', models.CharField(max_length=500, verbose_name='value')),
                ('legal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_attributes', to='about.aboutlegalinfo', verbose_name='legal section')),
            ],
            options={
                'verbose_name': 'org attribute',
                'verbose_name_plural': 'org attributes',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
