# Generated by Django 5.2.4 on 2026-08-02 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_ecosystem_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta1_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA 1 label'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta1_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 1 URL'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta2_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA 2 label'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta2_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 2 URL'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta3_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA 3 label'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='cta3_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='CTA 3 URL'),
        ),
        migrations.AddField(
            model_name='aboutcontactbanner',
            name='quote_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='quote text'),
        ),
        migrations.CreateModel(
            name='AboutContactBannerStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='e.g. 500+', max_length=20, verbose_name='number')),
                ('label', models.CharField(help_text='e.g. Chuyên gia', max_length=100, verbose_name='label')),
                ('icon_key', models.CharField(blank=True, help_text='users, building, clipboard, clock, star, globe', max_length=50, verbose_name='icon key')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.aboutcontactbanner', verbose_name='banner')),
            ],
            options={
                'verbose_name': 'contact banner stat',
                'verbose_name_plural': 'contact banner stats',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
