# Generated by Django 5.2.4 on 2026-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='organization')),
                ('inquiry_type', models.CharField(choices=[('consulting', 'Tư vấn và thiết kế giải pháp'), ('research', 'Nghiên cứu và hợp tác chuyên môn'), ('training', 'Đào tạo và phát triển năng lực'), ('expert', 'Kết nối chuyên gia'), ('other', 'Nhu cầu khác')], max_length=30, verbose_name='inquiry type')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'Mới tiếp nhận'), ('in_progress', 'Đang xử lý'), ('completed', 'Đã hoàn tất')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'contact request',
                'verbose_name_plural': 'contact requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
