# Generated by Django 5.2.4 on 2026-09-14 16:17

from django.db import migrations, models


def create_default_email_settings(apps, schema_editor):
    EmailSettings = apps.get_model('contact', 'EmailSettings')
    EmailSettings.objects.get_or_create(
        pk=1,
        defaults={
            'enabled': False,
            'host': 'smtp.gmail.com',
            'port': 587,
            'security': 'tls',
            'username': 'supportirdm@gmail.com',
            'from_name': 'Website IRDM',
            'from_email': 'supportirdm@gmail.com',
            'contact_recipient': 'vienncptnlv@irdm.edu.vn',
            'timeout': 10,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='enable email notifications')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('security', models.CharField(choices=[('tls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'No encryption')], default='tls', max_length=10, verbose_name='security')),
                ('username', models.EmailField(blank=True, max_length=254, verbose_name='SMTP username')),
                ('encrypted_password', models.TextField(blank=True, editable=False, verbose_name='encrypted SMTP password')),
                ('from_name', models.CharField(default='Website IRDM', max_length=100, verbose_name='sender name')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='sender email')),
                ('contact_recipient', models.EmailField(default='vienncptnlv@irdm.edu.vn', max_length=254, verbose_name='contact notification recipient')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='timeout (seconds)')),
                ('last_tested_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last tested at')),
                ('last_test_succeeded', models.BooleanField(editable=False, null=True, verbose_name='last test succeeded')),
                ('last_test_message', models.CharField(blank=True, editable=False, max_length=500, verbose_name='last test message')),
            ],
            options={
                'verbose_name': 'email configuration',
                'verbose_name_plural': 'email configuration',
            },
        ),
        migrations.RunPython(create_default_email_settings, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='email attempts'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_error',
            field=models.TextField(blank=True, verbose_name='email error'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent at'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Email disabled')], db_index=True, default='pending', max_length=20, verbose_name='email notification status'),
        ),
    ]
