# Generated by Django 5.2.12 on 2026-07-03 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'footer section',
                'verbose_name_plural': 'footer sections',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=200, verbose_name='site name')),
                ('site_tagline', models.CharField(blank=True, max_length=400, verbose_name='site tagline')),
                ('site_description', models.TextField(blank=True, verbose_name='site description')),
                ('logo', models.ImageField(blank=True, upload_to='core/logo/', verbose_name='logo')),
                ('logo_white', models.ImageField(blank=True, upload_to='core/logo/', verbose_name='logo (white)')),
                ('favicon', models.ImageField(blank=True, upload_to='core/logo/', verbose_name='favicon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='address')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='open in new tab')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'footer link',
                'verbose_name_plural': 'footer links',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], db_index=True, max_length=20, verbose_name='menu')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='open in new tab')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='parent item')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
