# Generated by Django 5.2.4 on 2026-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='map embed URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='operating hours'),
        ),
    ]
