# Generated by Django 5.2.4 on 2026-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
    ]
