# Generated by Django 5.2.4 on 2026-07-04 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionApproachStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'solution approach step',
                'verbose_name_plural': 'solution approach steps',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionListingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_label', models.CharField(blank=True, max_length=200, verbose_name='section label')),
                ('heading', models.CharField(max_length=300, verbose_name='heading')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cta_primary_label', models.CharField(blank=True, max_length=100, verbose_name='primary CTA label')),
                ('cta_primary_url', models.CharField(blank=True, max_length=500, verbose_name='primary CTA URL')),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100, verbose_name='secondary CTA label')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=500, verbose_name='secondary CTA URL')),
                ('quicknav_heading', models.CharField(blank=True, max_length=300, verbose_name='quick-nav heading')),
                ('approach_label', models.CharField(blank=True, max_length=200, verbose_name='approach section label')),
                ('approach_heading', models.CharField(blank=True, max_length=300, verbose_name='approach heading')),
                ('approach_description', models.TextField(blank=True, verbose_name='approach description')),
            ],
            options={
                'verbose_name': 'solution listing page',
                'verbose_name_plural': 'solution listing pages',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('section_label', models.CharField(blank=True, max_length=200, verbose_name='section label')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('thumbnail', models.ImageField(blank=True, upload_to='solution/thumbnails/', verbose_name='thumbnail')),
                ('hero_image', models.ImageField(blank=True, upload_to='solution/hero/', verbose_name='hero image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('challenge_label', models.CharField(default='Các thách thức trọng tâm', max_length=200, verbose_name='challenge label')),
                ('methodology_label', models.CharField(default='Viện IRDM đồng hành như thế nào?', max_length=200, verbose_name='methodology label')),
                ('output_label', models.CharField(default='Đầu ra có thể bao gồm', max_length=200, verbose_name='output label')),
                ('capability_label', models.CharField(default='Năng lực liên quan', max_length=200, verbose_name='capability label')),
                ('cta_heading', models.CharField(blank=True, max_length=200, verbose_name='CTA heading')),
                ('cta_sub', models.CharField(blank=True, max_length=200, verbose_name='CTA sub-heading')),
                ('cta_primary_label', models.CharField(blank=True, max_length=100, verbose_name='primary CTA label')),
                ('cta_primary_url', models.CharField(blank=True, max_length=500, verbose_name='primary CTA URL')),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100, verbose_name='secondary CTA label')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=500, verbose_name='secondary CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='meta keywords')),
                ('related_capabilities', models.ManyToManyField(blank=True, related_name='solutions', to='capability.capability', verbose_name='related capabilities')),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'solutions',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='solution.solution', verbose_name='solution')),
            ],
            options={
                'verbose_name': 'solution challenge',
                'verbose_name_plural': 'solution challenges',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='solution.solution', verbose_name='solution')),
            ],
            options={
                'verbose_name': 'solution feature',
                'verbose_name_plural': 'solution features',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionMethodologyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_steps', to='solution.solution', verbose_name='solution')),
            ],
            options={
                'verbose_name': 'solution methodology step',
                'verbose_name_plural': 'solution methodology steps',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='solution.solution', verbose_name='solution')),
            ],
            options={
                'verbose_name': 'solution output',
                'verbose_name_plural': 'solution outputs',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
