# Generated by Django 5.2.4 on 2026-07-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionlistingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the listing page hero section.', upload_to='solution/listing/', verbose_name='hero image'),
        ),
    ]
