# Generated by Django 5.2.4 on 2026-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_add_listing_page_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Background image for the CTA section at the bottom of the detail page.', upload_to='solution/cta/', verbose_name='CTA background image'),
        ),
        migrations.AddField(
            model_name='solutionlistingpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='solutionlistingpage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='solutionlistingpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='solutionlistingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Illustration shown in the right column of the hero section.', upload_to='solution/listing/', verbose_name='hero image'),
        ),
    ]
