# Generated by Django 5.2.4 on 2026-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_add_cta_image_and_listing_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionmethodologystep',
            name='description',
            field=models.TextField(blank=True, help_text='Full text of this IRDM action step.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='solutionoutput',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo illustrating this output (shown on the output card).', upload_to='solution/outputs/', verbose_name='output image'),
        ),
    ]
