# Generated by Django 5.2.4 on 2026-07-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_add_output_image_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='card_color',
            field=models.CharField(blank=True, default='', help_text='Tailwind gradient classes shown when no thumbnail is uploaded. Example: from-blue-900 to-blue-950', max_length=200, verbose_name='card color'),
        ),
    ]
