# Generated by Django 5.2.4 on 2026-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_add_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionapproachstep',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionapproachstep',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionchallenge',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionchallenge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionfeature',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionfeature',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionlistingpage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionlistingpage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionmethodologystep',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionmethodologystep',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='solutionoutput',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='solutionoutput',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
    ]
