# Generated by Django 5.2.12 on 2026-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='filter_section_description',
            field=models.TextField(blank=True, verbose_name='filter section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='filter_section_heading',
            field=models.CharField(blank=True, max_length=300, verbose_name='filter section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='hero_cta_primary_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='hero CTA primary label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='hero_cta_primary_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='hero CTA primary URL'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='hero_cta_secondary_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='hero CTA secondary label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='hero_cta_secondary_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='hero CTA secondary URL'),
        ),
        migrations.AddField(
            model_name='knowledgetopic',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Thumbnail shown on topic browse cards.', upload_to='knowledge/topics/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='knowledgelistingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Right-side illustration image in the hero section.', upload_to='knowledge/listing/', verbose_name='hero image / illustration'),
        ),
    ]
