# Generated by Django 5.2.4 on 2026-07-17 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_add_hero_cta_filter_topic_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFilterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Nhãn hiển thị phía trên nhóm, e.g. THEO LOẠI NỘI DUNG.', max_length=200, verbose_name='group title')),
                ('param_key', models.SlugField(help_text='Tên URL query param dùng cho nhóm này, e.g. ctype, topic, partner.', unique=True, verbose_name='URL param key')),
            ],
            options={
                'verbose_name': 'filter group',
                'verbose_name_plural': 'filter groups',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='search_placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text inside the search box.', max_length=200, verbose_name='search placeholder'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgedownload',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgedownload',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgefeaturedarticle',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgefeaturedarticle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgelistingpage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgelistingpage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgenewsitem',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgenewsitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgetopic',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgetopic',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.CreateModel(
            name='KnowledgeFilterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('value', models.CharField(help_text='Slug value dùng làm URL query param value.', max_length=200, verbose_name='value')),
                ('color_default', models.CharField(default='#6b7280', help_text='Màu border & text mặc định (hex), e.g. #6b7280.', max_length=30, verbose_name='default color')),
                ('color_active', models.CharField(default='#f97316', help_text='Màu border & text khi active (hex), e.g. #f97316.', max_length=30, verbose_name='active color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.knowledgefiltergroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'filter item',
                'verbose_name_plural': 'filter items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
                'unique_together': {('group', 'value')},
            },
        ),
    ]
