# Generated by Django 5.2.4 on 2026-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledge_filter_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefeaturedarticle',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Nhãn badge trên ảnh card. Nếu trống, dùng tên category của bài viết.', max_length=100, verbose_name='badge text'),
        ),
        migrations.AddField(
            model_name='knowledgefeaturedarticle',
            name='cta_icon',
            field=models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('download', 'Download ↓'), ('external', 'External ↗')], default='arrow-right', max_length=50, verbose_name='CTA icon'),
        ),
        migrations.AddField(
            model_name='knowledgefeaturedarticle',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Ví dụ: Đọc bài viết, Đăng ký tải tài liệu, Xem sự kiện', max_length=200, verbose_name='CTA text'),
        ),
        migrations.AddField(
            model_name='knowledgefeaturedarticle',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Nếu trống, dùng URL của bài viết.', max_length=500, verbose_name='CTA URL override'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='featured_bg_decoration',
            field=models.ImageField(blank=True, help_text='Họa tiết trang trí (dots, circles) hiển thị phía sau card.', upload_to='knowledge/featured/deco/', verbose_name='featured section decoration'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='featured_bg_image',
            field=models.ImageField(blank=True, help_text='Ảnh nền phía sau section Nội dung nổi bật.', upload_to='knowledge/featured/bg/', verbose_name='featured section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='featured_section_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị dưới tiêu đề section Nội dung nổi bật.', verbose_name='featured section description'),
        ),
    ]
