# Generated by Django 5.2.4 on 2026-07-18 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_featured_section_cms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_bg_decoration',
            field=models.ImageField(blank=True, upload_to='knowledge/content_type/deco/', verbose_name='content type section decorative background'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_bg_image',
            field=models.ImageField(blank=True, upload_to='knowledge/content_type/bg/', verbose_name='content type section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_cta_icon',
            field=models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('external', 'External ↗')], max_length=50, verbose_name='content type section CTA icon'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='content type section CTA text'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_cta_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='content type section CTA URL'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_description',
            field=models.TextField(blank=True, verbose_name='content type section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_heading',
            field=models.CharField(blank=True, max_length=300, verbose_name='content type section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='content_type_section_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='content type section label'),
        ),
        migrations.CreateModel(
            name='KnowledgeContentTypeCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh đại diện hiển thị trên đầu card.', upload_to='knowledge/content_type/cards/', verbose_name='cover image')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('cta_text', models.CharField(blank=True, help_text='Ví dụ: Xem nội dung liên quan', max_length=200, verbose_name='CTA text')),
                ('cta_icon', models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('download', 'Download ↓'), ('external', 'External ↗')], default='arrow-right', max_length=50, verbose_name='CTA icon')),
                ('cta_url', models.CharField(blank=True, help_text='URL khi nhấn CTA. Ví dụ: ?ctype=cong-bo-nghien-cuu', max_length=500, verbose_name='CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('category', models.ForeignKey(blank=True, help_text='Liên kết tới loại nội dung (dùng làm nhãn category trên card).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_cards', to='knowledge.knowledgecategory', verbose_name='category')),
                ('listing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_cards', to='knowledge.knowledgelistingpage', verbose_name='listing page')),
                ('tags', models.ManyToManyField(blank=True, help_text='Các chủ đề hiển thị dưới dạng tag trên card.', related_name='content_type_cards', to='knowledge.knowledgetopic', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'content type card',
                'verbose_name_plural': 'content type cards',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
