# Generated by Django 5.2.4 on 2026-07-18 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_content_type_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTopicCardTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for tag chip, e.g. #3b82f6.', max_length=30, verbose_name='color')),
            ],
            options={
                'verbose_name': 'topic card tag',
                'verbose_name_plural': 'topic card tags',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='topic_section_bg_decoration',
            field=models.ImageField(blank=True, upload_to='knowledge/topic_section/deco/', verbose_name='topic section decorative background'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='topic_section_bg_image',
            field=models.ImageField(blank=True, upload_to='knowledge/topic_section/bg/', verbose_name='topic section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='topic_section_description',
            field=models.TextField(blank=True, verbose_name='topic section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='topic_section_heading',
            field=models.CharField(blank=True, max_length=300, verbose_name='topic section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='topic_section_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='topic section label'),
        ),
        migrations.CreateModel(
            name='KnowledgeTopicCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh đại diện hiển thị trên đầu card.', upload_to='knowledge/topic_cards/', verbose_name='cover image')),
                ('icon', models.CharField(blank=True, help_text='Icon key để render SVG, e.g. heart, academic-cap, globe-alt, cpu-chip, users.', max_length=100, verbose_name='icon')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cta_text', models.CharField(blank=True, help_text='Ví dụ: Xem nội dung liên quan', max_length=200, verbose_name='CTA text')),
                ('cta_icon', models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('download', 'Download ↓'), ('external', 'External ↗')], default='arrow-right', max_length=50, verbose_name='CTA icon')),
                ('cta_url', models.CharField(blank=True, help_text='URL khi nhấn CTA. Ví dụ: ?topic=y-te', max_length=500, verbose_name='CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('listing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_cards', to='knowledge.knowledgelistingpage', verbose_name='listing page')),
                ('topic', models.ForeignKey(blank=True, help_text='Liên kết taxonomy topic để filter bài viết khi click CTA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_cards', to='knowledge.knowledgetopic', verbose_name='linked topic')),
                ('tags', models.ManyToManyField(blank=True, help_text='Các tag hiển thị dưới dạng chip trên card.', related_name='topic_cards', to='knowledge.knowledgetopiccardtag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'topic card',
                'verbose_name_plural': 'topic cards',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
