# Generated by Django 5.2.4 on 2026-07-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_topic_browse_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('organization', models.CharField(max_length=300, verbose_name='organization')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
            ],
            options={
                'verbose_name': 'download request',
                'verbose_name_plural': 'download requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_address',
            field=models.TextField(blank=True, verbose_name='contact address'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_city_image',
            field=models.ImageField(blank=True, help_text='Ảnh skyline thành phố hiển thị phía dưới contact block.', upload_to='knowledge/pub/city/', verbose_name='contact block city image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_cta_icon',
            field=models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('external', 'External ↗')], default='arrow-right', max_length=50, verbose_name='contact CTA icon'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_cta_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='contact CTA text'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_cta_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='contact CTA URL'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_description',
            field=models.TextField(blank=True, verbose_name='contact block description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_contact_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='contact block title'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_button_icon',
            field=models.CharField(blank=True, choices=[('send', 'Send ✉'), ('arrow-right', 'Arrow Right →')], default='send', max_length=50, verbose_name='form button icon'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_button_text',
            field=models.CharField(blank=True, default='Gửi yêu cầu', max_length=100, verbose_name='form button text'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_description',
            field=models.TextField(blank=True, verbose_name='form description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_email_label',
            field=models.CharField(blank=True, default='Email', max_length=100, verbose_name='email field label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_email_placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='email field placeholder'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_name_label',
            field=models.CharField(blank=True, default='Họ và tên', max_length=100, verbose_name='name field label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_name_placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='name field placeholder'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_note_label',
            field=models.CharField(blank=True, default='Ghi chú', max_length=100, verbose_name='note field label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_note_placeholder',
            field=models.TextField(blank=True, verbose_name='note field placeholder'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_org_label',
            field=models.CharField(blank=True, default='Đơn vị công tác', max_length=100, verbose_name='org field label'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_org_placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='org field placeholder'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_privacy_note',
            field=models.TextField(blank=True, verbose_name='form privacy note'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_success_message',
            field=models.TextField(blank=True, verbose_name='form success message'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_form_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='form title'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_section_bg_decoration',
            field=models.ImageField(blank=True, help_text='Họa tiết trang trí (dots, circles) hiển thị phía sau nội dung.', upload_to='knowledge/pub/deco/', verbose_name='publication section decorative background'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ảnh nền toàn section (ví dụ: cityscape, globe illustration).', upload_to='knowledge/pub/bg/', verbose_name='publication section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_section_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị dưới tiêu đề section.', verbose_name='publication section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_section_heading',
            field=models.CharField(blank=True, help_text='Tiêu đề section, e.g. Tài liệu tải về.', max_length=300, verbose_name='publication section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='pub_section_label',
            field=models.CharField(blank=True, help_text='Label nhỏ phía trên tiêu đề, e.g. Ấn phẩm & Báo cáo.', max_length=200, verbose_name='publication section label'),
        ),
    ]
