# Generated by Django 5.2.4 on 2026-07-19 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_publication_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAccordionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accordion_type', models.CharField(choices=[('post_event', 'Tổng hợp sau sự kiện'), ('cooperation', 'Công bố hợp tác')], db_index=True, default='post_event', max_length=20, verbose_name='accordion type')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('content', models.TextField(help_text='Nội dung accordion. Hỗ trợ văn bản thông thường, mỗi dòng là một đoạn.', verbose_name='content')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'accordion item',
                'verbose_name_plural': 'accordion items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEventTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#3b82f6', help_text='Màu nền badge tag, e.g. #3b82f6.', max_length=30, verbose_name='color (hex)')),
            ],
            options={
                'verbose_name': 'event tag',
                'verbose_name_plural': 'event tags',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_activity_heading',
            field=models.CharField(blank=True, default='Tin hoạt động IRDM', help_text='Tiêu đề cột trái — danh sách tin hoạt động.', max_length=200, verbose_name='activity news heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_events_heading',
            field=models.CharField(blank=True, default='Sự kiện sắp diễn ra', help_text='Tiêu đề cột phải — danh sách sự kiện.', max_length=200, verbose_name='upcoming events heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_section_bg_decoration',
            field=models.ImageField(blank=True, help_text='Họa tiết trang trí hiển thị phía sau nội dung.', upload_to='knowledge/news_section/deco/', verbose_name='news section decorative background'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ảnh nền toàn section.', upload_to='knowledge/news_section/bg/', verbose_name='news section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_section_description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn hiển thị dưới tiêu đề section.', verbose_name='news section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_section_heading',
            field=models.CharField(blank=True, help_text='Tiêu đề section, e.g. Tin tức & Sự kiện.', max_length=300, verbose_name='news section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='news_section_label',
            field=models.CharField(blank=True, help_text='Label nhỏ phía trên, e.g. IRDM trên báo chí và diễn đàn chuyên môn.', max_length=200, verbose_name='news section label'),
        ),
        migrations.CreateModel(
            name='KnowledgeActivityNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Ảnh đại diện cho tin hoạt động.', upload_to='knowledge/activity_news/', verbose_name='thumbnail')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='published date')),
                ('cta_text', models.CharField(blank=True, default='Xem chi tiết', max_length=100, verbose_name='CTA text')),
                ('cta_icon', models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('external', 'External ↗')], default='arrow-right', max_length=50, verbose_name='CTA icon')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_news', to='knowledge.knowledgecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'activity news item',
                'verbose_name_plural': 'activity news items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh bìa sự kiện.', upload_to='knowledge/events/', verbose_name='cover image')),
                ('event_date', models.CharField(blank=True, help_text='Chuỗi hiển thị ngày giờ sự kiện, e.g. 08/07/2026 - 11/07/2026.', max_length=200, verbose_name='event date (display text)')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, help_text='Địa điểm tổ chức, e.g. Viện IRDM (Thực tế).', max_length=300, verbose_name='location')),
                ('cta_text', models.CharField(blank=True, default='Xem sự kiện', max_length=100, verbose_name='CTA text')),
                ('cta_icon', models.CharField(blank=True, choices=[('arrow-right', 'Arrow Right →'), ('external', 'External ↗'), ('calendar', 'Calendar 📅')], default='arrow-right', max_length=50, verbose_name='CTA icon')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='knowledge.knowledgecategory', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='knowledge.knowledgeeventtag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'knowledge event',
                'verbose_name_plural': 'knowledge events',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
