# Generated by Django 5.2.4 on 2026-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_news_events_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeactivitynews',
            name='cta_target',
            field=models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_self', help_text='Mở link CTA trong tab nào, e.g. _self hoặc _blank.', max_length=20, verbose_name='CTA target'),
        ),
        migrations.AddField(
            model_name='knowledgeevent',
            name='cta_target',
            field=models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_self', help_text='Mở link CTA trong tab nào, e.g. _self hoặc _blank.', max_length=20, verbose_name='CTA target'),
        ),
    ]
