# Generated by Django 5.2.4 on 2026-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_add_cta_target_to_news_and_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='press_section_bg_image',
            field=models.ImageField(blank=True, help_text='Nhả nền tuỳ chọn cho section báo chí.', upload_to='knowledge/press/bg/', verbose_name='press section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='press_section_description',
            field=models.TextField(blank=True, verbose_name='press section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='press_section_heading',
            field=models.CharField(blank=True, help_text='Tiêu đề section, e.g. IRDM trên báo chí và diễn đàn chuyên môn.', max_length=300, verbose_name='press section heading'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='press_section_label',
            field=models.CharField(blank=True, help_text='Label nhỏ phía trên, e.g. BÁO CHÍ & DIỄN ĐÀN.', max_length=200, verbose_name='press section label'),
        ),
        migrations.AddField(
            model_name='knowledgenewsitem',
            name='cta_target',
            field=models.CharField(blank=True, choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_blank', help_text='Mở link CTA trong tab nào.', max_length=20, verbose_name='CTA target'),
        ),
        migrations.AddField(
            model_name='knowledgenewsitem',
            name='cta_text',
            field=models.CharField(blank=True, default='Xem chi tiết', max_length=100, verbose_name='CTA text'),
        ),
        migrations.AddField(
            model_name='knowledgenewsitem',
            name='is_press_article',
            field=models.BooleanField(db_index=True, default=False, help_text='Hiển thị bài trong section IRDM trên báo chí và diễn đàn chuyên môn.', verbose_name='is press article'),
        ),
    ]
