# Generated by Django 5.2.4 on 2026-07-19 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_add_press_section_and_news_cta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ảnh nền full-width của section.', upload_to='knowledge/ready/bg/', verbose_name='ready section background image'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_description',
            field=models.TextField(blank=True, verbose_name='ready section description'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_is_active',
            field=models.BooleanField(default=True, help_text='N/hiện toàn bộ section Sẵn sàng trao đổi.', verbose_name='ready section is active'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_overlay_color',
            field=models.CharField(blank=True, default='#0d1e4a', help_text='Màu overlay dạng hex, e.g. #0d1e4a.', max_length=30, verbose_name='ready section overlay color'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_overlay_opacity',
            field=models.FloatField(default=0.82, help_text='Độ mờ overlay từ 0.0 đến 1.0.', verbose_name='ready section overlay opacity'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle nhỏ phía trên, e.g. Sẵn sàng trao đổi?', max_length=200, verbose_name='ready section subtitle'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_text_color',
            field=models.CharField(blank=True, choices=[('light', 'Sáng (white)'), ('dark', 'Tối (dark)')], default='light', max_length=20, verbose_name='ready section text color'),
        ),
        migrations.AddField(
            model_name='knowledgelistingpage',
            name='ready_section_title',
            field=models.CharField(blank=True, help_text='Tiêu đề lớn của section CTA.', max_length=500, verbose_name='ready section title'),
        ),
        migrations.CreateModel(
            name='KnowledgeCTAButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200, verbose_name='button text')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='button URL')),
                ('target', models.CharField(choices=[('_self', 'Cùng tab (_self)'), ('_blank', 'Tab mới (_blank)')], default='_self', max_length=20, verbose_name='button target')),
                ('style', models.CharField(choices=[('primary', 'Primary (cam)'), ('secondary', 'Secondary (trắng/mờ)'), ('outline', 'Outline (viền trắng)')], default='primary', max_length=20, verbose_name='button style')),
                ('icon', models.CharField(blank=True, choices=[('', 'Không có'), ('arrow-right', 'Mũi tên →'), ('external', 'Mở ngoài ↗')], max_length=50, verbose_name='button icon')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('listing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta_buttons', to='knowledge.knowledgelistingpage', verbose_name='listing page')),
            ],
            options={
                'verbose_name': 'CTA button',
                'verbose_name_plural': 'CTA buttons',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
