# Generated by Django 5.2.4 on 2026-09-23 14:57

import uuid
from django.db import migrations, models


PARTNER_GROUPS = [
    ("co-quan-quan-ly", "Cơ quan quản lý", 1),
    ("he-thong-y-te", "Hệ thống y tế", 2),
    ("truong-dai-hoc", "Trường đại học", 3),
    ("doanh-nghiep", "Doanh nghiệp", 4),
    ("to-chuc-quoc-te", "Tổ chức quốc tế", 5),
]

ARTICLE_PARTNER_GROUPS = {
    "vi-sao-du-lieu-benh-vien-chua-de-chuyen-thanh-khcn": ["co-quan-quan-ly", "he-thong-y-te"],
    "suc-khoe-tam-than-nhan-vien-y-te-chiu-dung-khong-ben-vung": ["he-thong-y-te"],
    "green-university-green-hospital-quan-tri-ben-vung": ["he-thong-y-te", "truong-dai-hoc"],
    "cac-su-kien-chuyen-mon-sap-dien-ra-irdm": ["co-quan-quan-ly", "truong-dai-hoc", "doanh-nghiep", "to-chuc-quoc-te"],
    "cai-cach-he-thong-bao-hiem-y-te-bai-hoc-quoc-te": ["co-quan-quan-ly", "he-thong-y-te", "to-chuc-quoc-te"],
    "thiet-ke-chuong-trinh-dao-tao-nang-luc-lanh-dao-y-te": ["he-thong-y-te", "truong-dai-hoc"],
    "ai-trong-chan-doan-hinh-anh-y-te": ["he-thong-y-te", "doanh-nghiep"],
    "nhan-luc-y-te-tuong-lai-ky-nang-can-thiet": ["he-thong-y-te", "truong-dai-hoc"],
}


def populate_partner_groups(apps, schema_editor):
    partner_group_model = apps.get_model("knowledge", "KnowledgePartnerGroup")
    article_model = apps.get_model("knowledge", "KnowledgeArticle")
    partner_groups = {}

    for slug, label, display_order in PARTNER_GROUPS:
        partner_group, _ = partner_group_model.objects.update_or_create(
            slug=slug,
            defaults={
                "label": label,
                "display_order": display_order,
                "is_active": True,
            },
        )
        partner_groups[slug] = partner_group

    for article_slug, partner_slugs in ARTICLE_PARTNER_GROUPS.items():
        article = article_model.objects.filter(slug=article_slug).first()
        if article:
            article.partner_groups.set([partner_groups[slug] for slug in partner_slugs])


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_convert_body_to_rich_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePartnerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'knowledge partner group',
                'verbose_name_plural': 'knowledge partner groups',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='partner_groups',
            field=models.ManyToManyField(blank=True, related_name='articles', to='knowledge.knowledgepartnergroup', verbose_name='partner groups'),
        ),
        migrations.RunPython(populate_partner_groups, migrations.RunPython.noop),
    ]
