# Generated by Django 5.2.12 on 2026-07-03 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(choices=[('solutions', 'Featured Solutions'), ('capabilities', 'Featured Capabilities'), ('experts', 'Featured Experts'), ('insights', 'Featured Insights'), ('events', 'Featured Events'), ('resources', 'Featured Resources')], db_index=True, max_length=30, unique=True, verbose_name='section')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='subtitle')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA label')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='CTA URL')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'featured section config',
                'verbose_name_plural': 'featured section configs',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=300, verbose_name='heading')),
                ('subheading', models.CharField(blank=True, max_length=300, verbose_name='subheading')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('primary_cta_label', models.CharField(blank=True, max_length=100, verbose_name='primary CTA label')),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, verbose_name='primary CTA URL')),
                ('secondary_cta_label', models.CharField(blank=True, max_length=100, verbose_name='secondary CTA label')),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, verbose_name='secondary CTA URL')),
                ('background_image', models.ImageField(blank=True, upload_to='home/hero/', verbose_name='background image')),
            ],
            options={
                'verbose_name': 'hero section',
                'verbose_name_plural': 'hero sections',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('logo', models.ImageField(upload_to='home/partners/', verbose_name='logo')),
                ('website_url', models.URLField(blank=True, verbose_name='website URL')),
            ],
            options={
                'verbose_name': 'partner logo',
                'verbose_name_plural': 'partner logos',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='e.g. 200+', max_length=50, verbose_name='value')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Heroicon name, e.g. chart-bar', max_length=100, verbose_name='icon CSS class / name')),
            ],
            options={
                'verbose_name': 'statistic item',
                'verbose_name_plural': 'statistic items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
