# Generated by Django 5.2.12 on 2026-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_audiencesectionheader_audiencesegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencesegment',
            name='image',
            field=models.ImageField(blank=True, help_text='Illustration image shown on the audience card.', upload_to='home/audience/', verbose_name='card image'),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image shown at the bottom of the knowledge category card.', upload_to='home/knowledge/', verbose_name='card image'),
        ),
    ]
