# Generated by Django 5.2.4 on 2026-07-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_image_to_audience_and_knowledge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecapability',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL trang chi tiết năng lực, ví dụ: /vi/capability/nghien-cuu-ung-dung/', max_length=500, verbose_name='link URL'),
        ),
        migrations.AlterField(
            model_name='audiencesectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='audiencesectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='audiencetag',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='audiencetag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilitiessectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilitiessectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='corecapability',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='corecapability',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='evidencesectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='evidencesectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='featuredsectionconfig',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='featuredsectionconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='heropilltag',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='heropilltag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='knowledgesectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='knowledgesectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='methodologysectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='methodologysectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='methodologystep',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='methodologystep',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='philosophyprinciple',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='philosophyprinciple',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='philosophysectionheader',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='philosophysectionheader',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='statisticitem',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='statisticitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
    ]
