# Generated by Django 5.2.4 on 2026-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_link_url_to_corecapability'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecapability',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload ảnh icon (SVG/PNG, nền trong suốt). Nếu có sẽ thay thế icon mặc định.', upload_to='home/capability_icons/', verbose_name='icon image'),
        ),
    ]
