# Generated by Django 5.2.4 on 2026-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_icon_image_to_corecapability'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencesegment',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload ảnh icon (PNG/SVG nền trong suốt, ~56×56px). Hiển thị trong badge bo tròn trắng ở góc dưới ảnh card.', upload_to='home/audience_icons/', verbose_name='icon image'),
        ),
    ]
