# Generated by Django 5.2.4 on 2026-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_icon_image_to_audiencesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='heading_accent',
            field=models.CharField(blank=True, help_text='Remaining lines of the hero title — displayed in orange (#EC6D29)', max_length=300, verbose_name='heading lines 2-3 (orange)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Illustration displayed on the right panel, e.g. laptop/globe image', upload_to='home/hero/', verbose_name='hero illustration (right panel)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Used as a subtle full-section background overlay (opacity ~10%)', upload_to='home/hero/', verbose_name='background image (section overlay)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading',
            field=models.CharField(help_text='First line of the hero title — displayed in dark blue (#094977)', max_length=300, verbose_name='heading line 1 (dark)'),
        ),
    ]
