# Generated by Django 5.2.4 on 2026-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_herosection_heading_accent_herosection_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='quote_icon',
            field=models.ImageField(blank=True, help_text='Icon displayed next to the quote text (PNG/SVG ~24×24px). Falls back to default chat-bubble icon if empty.', upload_to='home/hero/icons/', verbose_name='quote icon'),
        ),
    ]
