# Generated by Django 5.2.4 on 2026-09-23 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_partner_page_content(apps, schema_editor):
    page_model = apps.get_model("home", "PartnerPageConfig")
    statistic_model = apps.get_model("home", "PartnerPageStatistic")
    cooperation_model = apps.get_model("home", "PartnerCooperationItem")
    evidence_model = apps.get_model("home", "EvidenceSectionHeader")
    homepage_statistic_model = apps.get_model("home", "StatisticItem")
    partner_logo_model = apps.get_model("home", "PartnerLogo")

    evidence = evidence_model.objects.filter(is_active=True).order_by("display_order").first()
    page = page_model.objects.create(
        meta_title="Đối tác",
        meta_description="Mạng lưới cơ quan quản lý, tổ chức y tế, trường đại học và doanh nghiệp đã đồng hành cùng Viện IRDM.",
        hero_label=evidence.section_label if evidence else "MẠNG LƯỚI HỢP TÁC",
        hero_heading=evidence.heading if evidence else "Các tổ chức IRDM đã đồng hành",
        hero_description=evidence.description if evidence else "Viện IRDM đồng hành cùng các tổ chức trong những bài toán thực tiễn.",
        hero_note="Mỗi quan hệ hợp tác được xây dựng trên sự thấu hiểu bối cảnh, mục tiêu rõ ràng và cam kết tạo ra kết quả có thể ứng dụng.",
        partners_label=evidence.partners_label if evidence else "ĐỐI TÁC TIÊU BIỂU",
        partners_heading="Một mạng lưới đa ngành, cùng chung mục tiêu phát triển",
        partners_description="IRDM trân trọng sự tin tưởng của các cơ quan, cơ sở y tế, trường đại học và doanh nghiệp trong những chương trình nghiên cứu và phát triển năng lực.",
        cooperation_label="CÁCH THỨC ĐỒNG HÀNH",
        cooperation_heading="Hợp tác từ bài toán thực tiễn",
        cooperation_description="IRDM cùng đối tác làm rõ nhu cầu, thiết kế hướng tiếp cận và chuyển hóa kết quả thành giải pháp có thể triển khai.",
        cta_label="CÙNG IRDM TẠO GIÁ TRỊ",
        cta_heading="Bạn đang tìm kiếm một đối tác chuyên môn phù hợp?",
        cta_description="Hãy chia sẻ bài toán của tổ chức để cùng xác định hướng hợp tác thiết thực.",
        cta_button_label="Trao đổi cùng IRDM",
        cta_button_url="/lien-he/",
        is_active=True,
    )
    page.partner_logos.set(partner_logo_model.objects.filter(is_active=True))

    homepage_statistics = homepage_statistic_model.objects.filter(is_active=True).order_by("display_order")
    for item in homepage_statistics:
        statistic_model.objects.create(
            page=page,
            value=item.value,
            label=item.label,
            display_order=item.display_order,
            is_active=True,
        )

    cooperation_items = [
        (1, "Nghiên cứu ứng dụng", "Khảo sát, phân tích dữ liệu và xây dựng bằng chứng phục vụ hoạch định và ra quyết định."),
        (2, "Tư vấn và thiết kế giải pháp", "Đồng thiết kế chương trình, mô hình và lộ trình phù hợp với bối cảnh vận hành của tổ chức."),
        (3, "Đào tạo và phát triển năng lực", "Xây dựng năng lực đội ngũ thông qua đào tạo, tập huấn và đồng hành triển khai tại đơn vị."),
        (4, "Kết nối chuyên gia", "Kết nối tri thức liên ngành và mạng lưới chuyên gia cho các sáng kiến cần chiều sâu chuyên môn."),
    ]
    for number, title, description in cooperation_items:
        cooperation_model.objects.create(
            page=page,
            number=number,
            title=title,
            description=description,
            display_order=number * 10,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_audiencesectionheader_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('meta_title', models.CharField(default='Đối tác', max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('hero_label', models.CharField(blank=True, max_length=200, verbose_name='hero label')),
                ('hero_heading', models.CharField(max_length=300, verbose_name='hero heading')),
                ('hero_description', models.TextField(blank=True, verbose_name='hero description')),
                ('hero_note', models.TextField(blank=True, verbose_name='hero note')),
                ('partners_label', models.CharField(blank=True, max_length=100, verbose_name='partners label')),
                ('partners_heading', models.CharField(max_length=300, verbose_name='partners heading')),
                ('partners_description', models.TextField(blank=True, verbose_name='partners description')),
                ('cooperation_label', models.CharField(blank=True, max_length=100, verbose_name='cooperation label')),
                ('cooperation_heading', models.CharField(max_length=300, verbose_name='cooperation heading')),
                ('cooperation_description', models.TextField(blank=True, verbose_name='cooperation description')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA section label')),
                ('cta_heading', models.CharField(max_length=300, verbose_name='CTA heading')),
                ('cta_description', models.TextField(blank=True, verbose_name='CTA description')),
                ('cta_button_label', models.CharField(max_length=100, verbose_name='CTA button label')),
                ('cta_button_url', models.CharField(default='/lien-he/', max_length=500, verbose_name='CTA button URL')),
                ('partner_logos', models.ManyToManyField(blank=True, help_text='Leave empty to display all active partner logos.', related_name='partner_pages', to='home.partnerlogo', verbose_name='partner logos')),
            ],
            options={
                'verbose_name': 'partner page configuration',
                'verbose_name_plural': 'partner page configuration',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCooperationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation_items', to='home.partnerpageconfig', verbose_name='partner page')),
            ],
            options={
                'verbose_name': 'partner cooperation item',
                'verbose_name_plural': 'partner cooperation items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerPageStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='home.partnerpageconfig', verbose_name='partner page')),
            ],
            options={
                'verbose_name': 'partner page statistic',
                'verbose_name_plural': 'partner page statistics',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.RunPython(create_partner_page_content, migrations.RunPython.noop),
    ]
