# Generated by Django 5.2.4 on 2026-07-04 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('summary', models.TextField(blank=True, help_text='Short description shown on the listing card.', verbose_name='summary')),
                ('thumbnail', models.ImageField(blank=True, upload_to='capability/thumbnails/', verbose_name='thumbnail')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image for the detail page hero.', upload_to='capability/hero/', verbose_name='hero image')),
                ('section_label', models.CharField(blank=True, help_text="Small label above the heading, e.g. 'Nền tảng chuyên môn'", max_length=200, verbose_name='section label')),
                ('description', models.TextField(blank=True, help_text='Detailed description for the detail page hero.', verbose_name='description')),
                ('what_is_label', models.CharField(default='Năng lực này là gì?', max_length=200, verbose_name="'What is' section label")),
                ('what_is_description', models.TextField(blank=True, verbose_name="'What is' description")),
                ('need_section_label', models.CharField(default='Khi nào tổ chức cần năng lực này?', max_length=200, verbose_name="'When needed' section label")),
                ('how_label', models.CharField(default='Viện IRDM đồng hành như thế nào?', max_length=200, verbose_name="'How IRDM helps' section label")),
                ('output_label', models.CharField(default='Đầu ra có thể bao gồm', max_length=200, verbose_name="'Outputs' section label")),
                ('cta_primary_label', models.CharField(blank=True, max_length=100, verbose_name='primary CTA label')),
                ('cta_primary_url', models.CharField(blank=True, max_length=500, verbose_name='primary CTA URL')),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100, verbose_name='secondary CTA label')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=500, verbose_name='secondary CTA URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='meta keywords')),
            ],
            options={
                'verbose_name': 'capability',
                'verbose_name_plural': 'capabilities',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityListingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_label', models.CharField(blank=True, max_length=200, verbose_name='section label')),
                ('heading', models.CharField(max_length=300, verbose_name='heading')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('overview_heading', models.CharField(blank=True, max_length=300, verbose_name='overview heading')),
                ('overview_description', models.TextField(blank=True, verbose_name='overview description')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA label')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='CTA URL')),
            ],
            options={
                'verbose_name': 'capability listing page',
                'verbose_name_plural': 'capability listing pages',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityCaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='number')),
                ('category_label', models.CharField(blank=True, help_text="e.g. 'Bệnh viện & KHCN'", max_length=200, verbose_name='category label')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cta_primary_label', models.CharField(blank=True, max_length=100, verbose_name='primary CTA label')),
                ('cta_primary_url', models.CharField(blank=True, max_length=500, verbose_name='primary CTA URL')),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100, verbose_name='secondary CTA label')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=500, verbose_name='secondary CTA URL')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='capability.capability', verbose_name='capability')),
            ],
            options={
                'verbose_name': 'capability case study',
                'verbose_name_plural': 'capability case studies',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityCaseStudyTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='capability.capabilitycasestudy', verbose_name='case study')),
            ],
            options={
                'verbose_name': 'case study tag',
                'verbose_name_plural': 'case study tags',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='capability.capability', verbose_name='capability')),
            ],
            options={
                'verbose_name': 'capability feature',
                'verbose_name_plural': 'capability features',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityHowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('icon', models.CharField(blank=True, help_text='Heroicon name, e.g. magnifying-glass', max_length=100, verbose_name='icon')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_steps', to='capability.capability', verbose_name='capability')),
            ],
            options={
                'verbose_name': 'capability how step',
                'verbose_name_plural': 'capability how steps',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityNeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_items', to='capability.capability', verbose_name='capability')),
            ],
            options={
                'verbose_name': 'capability need item',
                'verbose_name_plural': 'capability need items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='capability.capability', verbose_name='capability')),
            ],
            options={
                'verbose_name': 'capability output',
                'verbose_name_plural': 'capability outputs',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
