# Generated by Django 5.2.4 on 2026-07-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='card_icon',
            field=models.ImageField(blank=True, help_text='Small icon (PNG/SVG ~40×40 px) shown in frosted-glass box on the listing card top-left.', upload_to='capability/icons/', verbose_name='card icon'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilitycasestudy',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilitycasestudy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilitycasestudytag',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilitycasestudytag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilityfeature',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilityfeature',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilityhowstep',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilityhowstep',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilitylistingpage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilitylistingpage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilityneeditem',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilityneeditem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='capabilityoutput',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='capabilityoutput',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
    ]
