# Generated by Django 5.2.4 on 2026-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0002_add_card_icon_to_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='need_section_intro',
            field=models.TextField(blank=True, help_text="Intro paragraph shown on the left column of the 'When needed' section.", verbose_name="'When needed' intro text"),
        ),
        migrations.AddField(
            model_name='capability',
            name='what_is_image',
            field=models.ImageField(blank=True, help_text="Infographic/diagram shown on the left side of the 'What is' section.", upload_to='capability/what-is/', verbose_name="'What is' illustration"),
        ),
        migrations.AddField(
            model_name='capabilitycasestudy',
            name='image',
            field=models.ImageField(blank=True, help_text='Full-width photo shown on the case study card (landscape ~16:9).', upload_to='capability/case-studies/', verbose_name='case study image'),
        ),
        migrations.AddField(
            model_name='capabilityhowstep',
            name='step_image',
            field=models.ImageField(blank=True, help_text='Photo shown at the top of the how-step card (landscape ~16:9).', upload_to='capability/how-steps/', verbose_name='step photo'),
        ),
        migrations.AddField(
            model_name='capabilitylistingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Full-width background photo in the listing page hero section.', upload_to='capability/listing/', verbose_name='hero background image'),
        ),
    ]
