# Generated by Django 5.2.12 on 2026-07-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0003_add_image_fields_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityhowstep',
            name='icon_image',
            field=models.FileField(blank=True, help_text='Upload SVG hoặc PNG icon (khuyến nghị: SVG 24×24px). Nếu có, sẽ ưu tiên hiển thị thay icon text.', upload_to='capability/how-step-icons/', verbose_name='icon image'),
        ),
    ]
