# Generated by Django 5.2.4 on 2026-08-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0004_capability_icon_name'),
        ('capability', '0005_capabilitylistingpage_cta_section'),
    ]

    operations = [
    ]
